CREATE TABLE IF NOT EXISTS "JAVAEE"."CUSTOMERS"
(	"ID" RAW(16) DEFAULT sys_guid() NOT NULL ENABLE,
   "LOGIN" VARCHAR2(25 BYTE) NOT NULL ENABLE,
   "PASSWORD" VARCHAR2(255 BYTE) NOT NULL ENABLE,
  CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS"  ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;

CREATE TABLE IF NOT EXISTS "JAVAEE"."ACCOUNTS"
(	"ID" RAW(16) DEFAULT sys_guid() NOT NULL ENABLE,
   "ACCOUNT_NUMBER" VARCHAR2(100 BYTE) NOT NULL ENABLE,
   "BALANCE" NUMBER(19,4) DEFAULT 0 NOT NULL ENABLE,
   "NAME" VARCHAR2(255 BYTE) NOT NULL ENABLE,
   "BLOCKED_AMOUNT" NUMBER(19,4),
   "CURRENCY_ID" RAW(16),
   "CUSTOMER_ID" RAW(16) NOT NULL ENABLE,
  CONSTRAINT "ACCOUNTS_PK" PRIMARY KEY ("ID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
    STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
    TABLESPACE "USERS"  ENABLE,
  CONSTRAINT "ACCOUNTS_FK1" FOREIGN KEY ("CUSTOMER_ID")
  REFERENCES "JAVAEE"."CUSTOMERS" ("ID") ENABLE
) SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "USERS" ;